# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: custom_averaging.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x16\x63ustom_averaging.proto\x12\x10\x63ustom_averaging"7\n\x12JoinBarrierRequest\x12\x10\n\x08group_id\x18\x01 \x01(\x0c\x12\x0f\n\x07peer_id\x18\x02 \x01(\x0c"J\n\x13JoinBarrierResponse\x12\x33\n\x04\x63ode\x18\x01 \x01(\x0e\x32%.custom_averaging.BarrierResponseCode"/\n\x1b\x42\x61rrierCompleteNotification\x12\x10\n\x08group_id\x18\x01 \x01(\x0c"N\n\x17\x42\x61rrierCompleteResponse\x12\x33\n\x04\x63ode\x18\x01 \x01(\x0e\x32%.custom_averaging.BarrierResponseCode*T\n\x13\x42\x61rrierResponseCode\x12\x0b\n\x07UNKNOWN\x10\x00\x12\x0c\n\x08\x41\x43\x43\x45PTED\x10\x01\x12\x0c\n\x08REJECTED\x10\x02\x12\x14\n\x10\x42\x41RRIER_COMPLETE\x10\x03\x62\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "custom_averaging_pb2", _globals)
if not _descriptor._USE_C_DESCRIPTORS:
    DESCRIPTOR._loaded_options = None
    _globals["_BARRIERRESPONSECODE"]._serialized_start = 306
    _globals["_BARRIERRESPONSECODE"]._serialized_end = 390
    _globals["_JOINBARRIERREQUEST"]._serialized_start = 44
    _globals["_JOINBARRIERREQUEST"]._serialized_end = 99
    _globals["_JOINBARRIERRESPONSE"]._serialized_start = 101
    _globals["_JOINBARRIERRESPONSE"]._serialized_end = 175
    _globals["_BARRIERCOMPLETENOTIFICATION"]._serialized_start = 177
    _globals["_BARRIERCOMPLETENOTIFICATION"]._serialized_end = 224
    _globals["_BARRIERCOMPLETERESPONSE"]._serialized_start = 226
    _globals["_BARRIERCOMPLETERESPONSE"]._serialized_end = 304
# @@protoc_insertion_point(module_scope)
